variables:
  DOCKER_DRIVER: overlay2
  
stages:
  - build
  - test
  - plan
  - deploy
  - script
  - deploy-env-1

.base_image:
  image: $RUNNER_CUSTOM_IMAGE
  
.cache_push:
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull-push
    
.cache_pull:
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull
    
.compile_base:
  extends:
    - .base_image
    - .cache_push
  stage: compile  
  except:
    - triggers
    - schedules  
  tags:
    - saas-linux-medium-amd64
    
.run_base:
  extends:
    - .base_image
    - .cache_pull
  except:
    - triggers
    - schedules  
  tags:
    - saas-linux-medium-amd64
    
.deploy_base:
  extends:
    - .base_image
    - .cache_pull
  only:
    variables:
      - $DEPLOYMENT     
  tags:
    - saas-linux-medium-amd64

.deployment_vars:
  stage: deploy-env-1
  variables:
    LOCATION: location_one	
    ENVIRONMENT: environment_one	

    
build_app:
  extends: .compile_base
  stage: build  
  script:
    - source scripts/build_all.sh
  
    
plan_deployment:
  extends: .run_base
  stage: plan  
  script:
    - source scripts/plan.sh
  artifacts:
    paths:
      - dag.json
      - pipeline.yml
    expire_in: 1 hour

deployment_env_1:
  extends: 
    - .deploy_base
    - .deployment_vars
  script:
    - source scripts/deploy.sh
    

#deploy:
#  extends: .run_base
#  stage: deploy  
#  trigger:
#    include:
#      - artifact: pipeline.yml
#        job: plan_deployment
#    strategy: depend
        
  
  

  
