variables:
  DOCKER_DRIVER: overlay2
  
stages:
  - build
  - test
  - plan
  - deploy
  - script
  - deploy-site-1
 
.base_image:
  image: $RUNNER_CUSTOM_IMAGE
  
.cache_push:
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull-push
    
.cache_pull:
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull
    
.compile_base:
  extends:
    - .base_image
    - .cache_push
  stage: compile  
  except:
    - triggers
    - schedules  
  tags:
    - saas-linux-medium-amd64
    
.run_base:
  extends:
    - .base_image
    - .cache_pull
  only:
    variables:
      - $DEPLOYMENT
  tags:
    - saas-linux-medium-amd64
    
   
build_app:
  extends: .compile_base
  stage: build  
  script:
    - source scripts/build_all.sh
  
    
plan_deployment:
  extends: .run_base
  stage: plan  
  script:
    - source scripts/plan.sh
  artifacts:
    paths:
      - dag.json
      - scripts/pipeline.yml
    expire_in: 1 hour

deploy:
  stage: deploy  
  only:
    variables:
      - $DEPLOYMENT
  trigger:
    include:
      - artifact: scripts/pipeline.yml
        job: plan_deployment
    strategy: depend
.deployment_base:
  extends:
    - .base_image
  tags:
    - saas-linux-medium-amd64
.deployment_vars_site_1:
  stage: deploy-site-1
  variables:
    LOCATION: us-east-1
    ENVIRONMENT: site_1_env
deployment_site_1:
  extends:
    - .deployment_base
    - .deployment_vars_site_1
  script:
    - source scripts/deploy.sh
        
  
  

  
