variables:
  DOCKER_DRIVER: overlay2
  
stages:
  - build
  - test
  - plan
  - deploy
  - script

.base_image:
  image: $RUNNER_CUSTOM_IMAGE
  
.cache_push:
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull-push
    
.cache_pull:
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull
    
.compile_base:
  extends:
    - .base_image
    - .cache_push
  stage: compile  
  except:
    - triggers
    - schedules  
  tags:
    - saas-linux-medium-amd64
    
.run_base:
  extends:
    - .base_image
    - .cache_pull
  except:
    - triggers
    - schedules  
  tags:
    - saas-linux-medium-amd64
    
   
build_app:
  extends: .compile_base
  stage: build  
  script:
    - source scripts/build_all.sh
  
    
plan_deployment:
  extends: .run_base
  stage: plan  
  script:
    - source scripts/plan.sh
  artifacts:
    paths:
      - dag.json
      - pipeline.yml
    expire_in: 1 hour

deploy:
  extends: .run_base
  stage: deploy  
  trigger:
    include:
      - artifact: pipeline.yml
        job: plan_deployment
    strategy: depend
        
  
  

  
